import { prisma } from "@/lib/db";
import { env } from "@/lib/env";
import { allowedActionsForTrust } from "@/lib/policy";

export async function POST(req: Request) {
  const body = await req.json().catch(() => ({}));
  const domain = body?.domain || env.NEXT_PUBLIC_DEMO_DOMAIN || "reliablenissan.com";
  const ruleSetId: string = body?.ruleSetId;
  if (!ruleSetId) return Response.json({ ok: false, error: "missing_ruleSetId" }, { status: 400 });

  const customer = await prisma.customer.findUnique({ where: { domain } });
  if (!customer) return Response.json({ ok: false, error: "customer_not_found" }, { status: 404 });

  const ruleSet = await prisma.ruleSet.findUnique({ where: { id: ruleSetId } });
  if (!ruleSet) return Response.json({ ok: false, error: "ruleset_not_found" }, { status: 404 });

  const trust = await prisma.trustScoreSnapshot.findFirst({ where: { customerId: customer.id }, orderBy: { createdAt: "desc" } });
  const trustTotal = trust?.total ?? 70;
  const policy = allowedActionsForTrust(trustTotal);

  await prisma.activityEvent.create({
    data: {
      customerId: customer.id,
      kind: "policy_checked",
      summary: `Policy checked for growth: trust ${trustTotal}/100 (${policy.zone}).`,
      payload: { trustTotal, policy },
    },
  });

  const requiresApproval = ruleSet.name.toLowerCase().includes("review request");

  // Deterministic sizes (align with preview logic)
  const segmentSize = ruleSet.name.toLowerCase().includes("referral") ? 42 : 120;
  const suppressedSize = ruleSet.name.toLowerCase().includes("review request") ? 18 : 6;

  const campaign = await prisma.campaign.create({
    data: {
      customerId: customer.id,
      ruleSetId: ruleSet.id,
      name: `Dry-run: ${ruleSet.name}`,
      goal: "Demonstrate trust-gated execution (dry-run by default)",
      status: "READY",
      dryRun: true,
      requiresApproval,
      segmentSize,
      suppressedSize,
      gatingSummary: { policy, trustTotal, requiresApproval } as any,
      messages: {
        create: {
          channel: "email",
          subject: `Demo: ${ruleSet.name}`,
          body: "This is a dry-run campaign generated by TrustEye. No messages were sent.",
        },
      },
    },
  });

  const to = Array.from({ length: Math.min(5, segmentSize) }).map((_, i) => `demo.segment+${i + 1}@example.com`);
  for (const recipient of to) {
    await prisma.sendReceipt.create({
      data: {
        campaignId: campaign.id,
        status: "DRY_RUN",
        to: recipient,
        channel: "email",
        provider: "simulated",
        payload: { ruleSetId: ruleSet.id } as any,
      },
    });
  }

  await prisma.activityEvent.create({
    data: {
      customerId: customer.id,
      kind: "campaign_created",
      summary: `Campaign created (dry-run) from rule: ${ruleSet.name}.`,
      payload: { campaignId: campaign.id, ruleSetId: ruleSet.id, toCount: to.length },
    },
  });

  await prisma.activityEvent.create({
    data: {
      customerId: customer.id,
      kind: "receipts_written",
      summary: `Dry-run receipts written (${to.length}).`,
      payload: { campaignId: campaign.id },
    },
  });

  return Response.json({ ok: true, campaignId: campaign.id, requiresApproval, segmentSize, suppressedSize });
}


